#!/usr/bin/env python3
"""Aggregate free OSS audit stack outputs into docs/FREE-OSS-AUDIT.md.

Prior-art verdict: Build stdlib-only. Supersedes docs/SAST.md.
See ~/.claude/state/prior-art-verdict.json for full audit record.
Called by .github/workflows/free-oss-audit.yml aggregate job.
"""
import json
from datetime import datetime, timezone
from pathlib import Path

HEADER = """\
# Free OSS Audit Stack -- Strongest-Available Free Substitute

> **Honest scope statement:** This is the free-tier elite-bar audit stack for the
> local-first single-binary MCP backbone. Accredited third-party SOC2 / ISO27001 /
> NCC pen-test are paid services explicitly out-of-scope per the project's free-only
> constraint. The stack below is what reproducibly proves the security posture; users
> with regulated procurement needs should engage their own auditor against the public repo.

Generated by `.github/workflows/free-oss-audit.yml`. Re-runs weekly + on every push to main.
"""

TOOLS = [
    ("cargo-audit",   "audit.json",    "cargo-audit -- RUSTSEC Advisory Scan"),
    ("semgrep",       "semgrep.json",  "semgrep -- SAST (p/rust + .semgrep.yml)"),
    ("cargo-fuzz",    "artifacts",     "cargo-fuzz -- Fuzzing (300s per target)"),
    ("cargo-mutants", "mutants.json",  "cargo-mutants -- Mutation Testing"),
    ("scorecard",     "scorecard.json","ossf-scorecard -- Supply-Chain Hygiene"),
]

GITLEAKS_NOTE = """\

## gitleaks -- Secret Scan

gitleaks exits non-zero on any finding; CI job status is the verdict surface.
No separate JSON artifact is collected. Check the workflow run logs for findings.
"""

MAX_JSON_PREVIEW = 3000


def _summarize_cargo_audit(data: dict) -> str:
    vulns = data.get("vulnerabilities", {})
    count = vulns.get("count", "?")
    found = vulns.get("found", [])
    lines = [f"**Vulnerabilities found:** {count}"]
    for v in found[:5]:
        pkg = v.get("package", {})
        adv = v.get("advisory", {})
        lines.append(
            f"- `{pkg.get('name','?')} {pkg.get('version','?')}` -- "
            f"[{adv.get('id','?')}]({adv.get('url','')}) {adv.get('title','')}"
        )
    if len(found) > 5:
        lines.append(f"- and {len(found) - 5} more (see full JSON artifact)")
    return "\n".join(lines)


def _summarize_semgrep(data: dict) -> str:
    results = data.get("results", [])
    errors = data.get("errors", [])
    lines = [f"**Findings:** {len(results)}  **Errors:** {len(errors)}"]
    for r in results[:5]:
        path = r.get("path", "?")
        line = r.get("start", {}).get("line", "?")
        rule = r.get("check_id", "?")
        lines.append(f"- `{path}:{line}` -- {rule}")
    if len(results) > 5:
        lines.append(f"- and {len(results) - 5} more (see full JSON artifact)")
    return "\n".join(lines)


def _summarize_scorecard(data: dict) -> str:
    score = data.get("score", "?")
    checks = data.get("checks", [])
    lines = [f"**Overall score:** {score}/10"]
    for c in sorted(checks, key=lambda x: x.get("score", 10)):
        name = c.get("name", "?")
        sc = c.get("score", "?")
        reason = c.get("reason", "")
        lines.append(f"- {name}: {sc}/10  -- {reason}")
    return "\n".join(lines)


def _resolve_artifact(tool_dir: str, json_file: str) -> "Path | None":
    for p in [Path(tool_dir) / json_file, Path(json_file)]:
        if p.exists():
            return p
    return None


def _render_tool(tool_dir: str, json_file: str, display: str) -> str:
    lines = [f"\n## {display}\n"]
    artifact = _resolve_artifact(tool_dir, json_file)
    if artifact is None:
        lines.append(
            "_Artifact missing -- job may have failed or produced no output. "
            "Check workflow run logs._\n"
        )
        return "\n".join(lines)
    try:
        data = json.loads(artifact.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        lines.append(f"_Could not parse artifact: {exc}_\n")
        return "\n".join(lines)
    if "audit" in json_file:
        lines.append(_summarize_cargo_audit(data))
    elif "semgrep" in json_file:
        lines.append(_summarize_semgrep(data))
    elif "scorecard" in json_file:
        lines.append(_summarize_scorecard(data))
    preview = json.dumps(data, indent=2)
    if len(preview) > MAX_JSON_PREVIEW:
        preview = preview[:MAX_JSON_PREVIEW] + "\n... (truncated -- see full artifact)"
    lines.append(
        f"\n<details><summary>Raw JSON</summary>\n\n```json\n{preview}\n```\n</details>\n"
    )
    return "\n".join(lines)


def main() -> None:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    print(HEADER)
    print(f"_Last updated: {ts}_\n")
    for tool_dir, json_file, display in TOOLS:
        if json_file == "artifacts":
            fuzz_dir = _resolve_artifact(tool_dir, "artifacts")
            found_dir = fuzz_dir if (fuzz_dir and fuzz_dir.is_dir()) else None
            crashes = list(found_dir.rglob("crash-*")) if found_dir else []
            print(f"\n## {display}\n")
            if crashes:
                print(f"**Crashes found: {len(crashes)}**")
                for c in crashes[:5]:
                    print(f"- `{c}`")
                if len(crashes) > 5:
                    print(f"- and {len(crashes) - 5} more (see full artifact)")
            else:
                print("No crashes found in fuzz artifact directory.\n")
            continue
        print(_render_tool(tool_dir, json_file, display))
    print(GITLEAKS_NOTE)


if __name__ == "__main__":
    main()